---
title: "Testing"
format: html
---
# Load Packages and Functions 

```{r}
#################### Load Packages and Functions #################### 
require(shiny)
require(shiny.fluent)
require(shiny.react)
require(shinyjs)
require(htmltools)
require(workflowsets)
require(plotly)
require(tidyverse)
require(ggpubr)
require(janitor)
require(DT)
require(rmarkdown)
require(shinyWidgets)
require(here)
require(RColorBrewer)
require(readxl)
require(openxlsx)
require(glue)
require(drc)
require(gt)
library(meltr)
# require(ggalt)

source(here::here("code/functions.R"))
```

# Load Data

```{r}
raw_file <- c(
  "/Users/argyropoulos.d/OneDrive - wehi.edu.au/2_Projects/#PvSeroTaT/App_Shiny/Data/conversion/ETH_data_ramin/Ethiop-plate1-200325_20250320_133643.xlsx",
  "/Users/argyropoulos.d/OneDrive - wehi.edu.au/2_Projects/#PvSeroTaT/App_Shiny/Data/conversion/ETH_data_ramin/Ethiop-plate2- 200325_20250320_154812.xlsx",
  "/Users/argyropoulos.d/OneDrive - wehi.edu.au/2_Projects/#PvSeroTaT/App_Shiny/Data/conversion/ETH_data_ramin/Ethiop-plate3-200325_20250320_163911.xlsx"
)
raw_file_names <- c(
  "Ethiop-plate1-200325_20250320_133643.xlsx",
  "Ethiop-plate2- 200325_20250320_154812.xlsx",
  "Ethiop-plate3-200325_20250320_163911.xlsx"
)
plate_file <- "/Users/argyropoulos.d/OneDrive - wehi.edu.au/2_Projects/#PvSeroTaT/App_Shiny/Data/conversion/ETH_data_ramin/Ethiopia Biobank samples-Clinical_2023.xlsx"

###################### Data processing ###################### 
serodata <- readSeroData(raw_file, raw_file_names, "magpix")
antigendata <- readAntigens(serodata)
plates <- readPlateLayout(plate_file, antigendata)

file <- raw_file[[1]]
file_extension <- tools::file_ext(file)  # Identify the file extension and read the file accordingly
      
      if (file_extension == "xlsx") {
        full <- suppressMessages(readxl::read_excel(file))
        df <- as.data.frame(full)
        
        data_raw <- df
        
        median_row_number     <- which(df$xPONENT == "Median")
        endmedian_row_number  <- which(df$xPONENT == "Net MFI")
        count_row_number      <- which(df$xPONENT == "Count")
        endcount_row_number   <- which(df$xPONENT == "Avg Net MFI")
        
        results <- suppressMessages(readxl::read_excel(file, skip = median_row_number + 1, n_max = endmedian_row_number - median_row_number - 2))
        counts <- suppressMessages(readxl::read_excel(file, skip = count_row_number + 1, n_max = endcount_row_number - count_row_number - 2, col_names = TRUE))
        run <- suppressMessages(readxl::read_excel(file, n_max = median_row_number))
        
      } else if (file_extension == "csv") {
        
        first_lines <- readLines(file, n = 5)           # Read the first few lines of the file
        
        if (any(grepl(";", first_lines))) {
          # IF EUROPEAN CSV WITH ; DELLIMITER 
          csv <- suppressWarnings(meltr::melt_csv2(file)) 
        } else { 
          # IF CONVENTIONAL CSV WITH , DELLIMITER 
          csv <-  suppressMessages(meltr::melt_csv(file))
        }
        
        full <- csv %>% 
          dplyr::select(-data_type) %>% 
          tidyr::pivot_wider(id_cols = row, names_from = col, values_from = value) %>% 
          dplyr::select(-row) 
        full <- filter(full, rowSums(is.na(full)) != ncol(full)) 
        
        df <- suppressWarnings(as.data.frame(full) %>% janitor::row_to_names(row_number = 1)) 
        data_raw <- df
        
        median_row_number     <- which(df$xPONENT == "Median")
        endmedian_row_number  <- which(df$xPONENT == "Net MFI")
        count_row_number      <- which(df$xPONENT == "Count")
        endcount_row_number   <- which(df$xPONENT == "Avg Net MFI")
        
        results <- df[(median_row_number + 1):(endmedian_row_number - 1), ]
        colnames(results) <- results[1, ]
        results <- results[-1, ]
        results <- results[, colSums(!is.na(results)) > 0] # remove NA columns
        results <- results[rowSums(!is.na(results)) > 0, ] # remove NA rows
        rownames(results) <- NULL
        
        counts <- df[(count_row_number + 1):(endcount_row_number - 1), ]
        counts <- counts[, colSums(!is.na(counts)) > 0] # remove NA columns
        counts <- counts[rowSums(!is.na(counts)) > 0, ] # remove NA rows
        colnames(counts) <- counts[1, ]
        counts <- counts[-1, ]
        rownames(counts) <- NULL
        
        run <- df[1:median_row_number, ]
        run <- run[, colSums(!is.na(run)) > 0] # remove NA columns
        run <- run[rowSums(!is.na(run)) > 0, ] # remove NA rows
        rownames(run) <- NULL
        
      } else {
        stop("Unsupported file format! Please use .csv or .xlsx")
      }
      
      # 2. Create results
      results <- results %>%
        dplyr::select(-dplyr::any_of("Total Events")) %>%
        dplyr::mutate(dplyr::across(everything(), ~ gsub("NaN", 0, .))) %>% # Change "NaN" to 0s
        dplyr::mutate(Sample = ifelse(Sample == "Blank", paste0("Blank", row_number()), 
                                      ifelse(Sample == "B", paste0("Blank", row_number()), Sample))) %>% # Sequentially relabel Blank rows and keep other Sample values unchanged
        dplyr::mutate(Sample = ifelse(Sample == "S", paste0("S", cumsum(Sample == "S")), Sample)) # Sequentially relabel Sample rows and keep other Sample values 
      
      # 3. Load counts for QC 
      counts <- counts %>%
        dplyr::mutate(Sample = ifelse(Sample == "Blank", paste0("Blank", row_number()), 
                                      ifelse(Sample == "B", paste0("Blank", row_number()), Sample))) %>% # Sequentially relabel Blank rows and keep other Sample values unchanged
        dplyr::select(-any_of("Total Events"))
      counts <- tidyr::as_tibble(counts)
      
      # 4. Save blanks
      blanks <- results %>% dplyr::filter(grepl("Blank|^B$", Sample, ignore.case = TRUE))
      
      # 5. Save standards
      stds <- results %>% dplyr::filter(grepl("^S", Sample, ignore.case = TRUE))
      
      # 6. Save run info 
      run_info <- as.data.frame(run) %>% dplyr::select(Program:xPONENT)
      
      # Ensure blanks exist
      if (nrow(blanks) == 0) {
        stop("No blanks were found in the dataset. Ensure blanks are properly labeled.")
      }
      
      # Ensure standards exist
      if (nrow(stds) == 0) {
        stop("No standards were found in the dataset. Ensure standards are properly labeled.")
      }
      
      # Save the plate number for this file 
      plate_numbers <- file_name %>% stringr::str_extract("(?i)(repeat)?plate\\d+(?=[._-]|$)")
      
      # Add 'plate' column to each dataframe
      data_raw$Plate <- plate_numbers
      results$Plate <- plate_numbers
      counts$Plate <- plate_numbers
      blanks$Plate <- plate_numbers
      stds$Plate <- plate_numbers        
      run_info$Plate <- plate_numbers
      
      # Add processed file's tables to the master list
      master_list$data_raw <- suppressMessages(dplyr::bind_rows(master_list$data_raw, data_raw))   # Combine raw data
      master_list$results  <- dplyr::bind_rows(master_list$results, results)     # Combine processed results
      master_list$counts   <- dplyr::bind_rows(master_list$counts, counts)       # Combine counts
      master_list$blanks   <- dplyr::bind_rows(master_list$blanks, blanks)       # Combine blanks
      master_list$stds     <- dplyr::bind_rows(master_list$stds, stds)           # Combine stds
      master_list$run      <- dplyr::bind_rows(master_list$run, run_info)        # Combine run
      
    } else {
      stop("Unsupported file type. Please use either Magpix or Bioplex!")
    }
  }
  
  return(master_list)
  
}

```

